// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "acme"
// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "acme.vmware.local"
// Base domain from which the cluster domain is a subdomain.
base_domain = "vmware.local"


vsphere_server = "vcsa.acme.vmware.local"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "VMware1!"
vsphere_cluster = "Cluster01"
vsphere_datacenter = "Prod-Cloud"
vsphere_datastore = "vsanDatastore"
vm_template = "rhcos-4.3.8-x86_64-vmware.x86_64"
vm_network = "ocp4-segment"
machine_cidr = "10.114.16.0/24"
bootstrap_ip = "10.114.16.9"
control_plane_ips = ["10.114.16.10", "10.114.16.11", "10.114.16.12"]
compute_ips = ["10.114.16.20", "10.114.16.21", "10.114.16.22"]

control_plane_count = 3
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://172.16.1.6/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.acme.vmware.local:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJRkJtUjk1U25RS3d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURVeE16SXdNakl3TjFvWApEVE13TURVeE1USXdNakl3TjFvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyVW5wSlpZSHdMY1YKeWJKclo2TnQvUHE1S1dYYVNIVU40RVl5blFTY3hhUDhJTzNEalRmVXBDeFVWWEpsR1hCVU9VYjduK2d3aXdwVwpBZnFvRW1XeWliYUVxS3d4djVaaFpVNGlSN002dWJGc0NIMWt3VnNRdDRBNFowSXhieFg2ZnVQYXhnT1dHdkhEClRUZ21hVDZneDJud1Y5bHZMNzlXSkd5MUJaTCtMcHlBaXZNR2U4bi9CTm9MeEJiZ2orRGZWN2M0eWI4RjNBM2cKOUtLU0Myd1ZRVWJHZHBCaWk1Mm45VFhRTW5XTjJNR09TQkVIcmYxVm5UazJyeFZMMWhEVmtxYjMzZHR5S2hWWgpINjloaS9QdXRHbUVmWEI0SVQ2ZGJCNStjR011M0pCZEtGdVpYeVMzbk1zS2x0ZUcwVWlmVzA5V253bGZIS2RiClIxcSt2MHFPTFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUExUEZ6UiswWk9aVmVJaW1EQy9GZGY2N08zb3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUZyVDk4Umc1NUhuWURoRzU0SFZDVXRKQ3MxRkNCSUJnNVVLeGFEMFlEakZ6dE9CeWZSazVZZmhUcG5aCmVVR2ZnYkU2WWc4K3dRQi9NL3FncHRodUpIa1FmZnRhTmkyTDd4bVorZ1NKdVZSNEVoeWZ1VTIvRzNadzhheTgKT1l0MEhOczZ5anNSMWF1bjM5aHFDQmdJenFWUVMyeVFrQUJaTVhpR09GamdFUmVyZWlWTUF4TEsvUGlrK0lNMAp6cFNyV2t3T01TSDZnd2pJU1BrNG00RTJxbVgxaFpDTExMYzRydTBuemJiYmNlMmdETG5qbTAvRWVFUklIZTNWCjdQaWhuRWoxajExUmRudVpBODFmQXQ4Y0p6Yk5TakMzTVdLVDBqWUxVcTBSUTdUV3l4N0cyUG5oUEc4WVQwaG0KcTd2RGFQUCt2UVJrMWlYb2VuMWgxb1l2eEdrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.acme.vmware.local:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJRkJtUjk1U25RS3d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURVeE16SXdNakl3TjFvWApEVE13TURVeE1USXdNakl3TjFvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyVW5wSlpZSHdMY1YKeWJKclo2TnQvUHE1S1dYYVNIVU40RVl5blFTY3hhUDhJTzNEalRmVXBDeFVWWEpsR1hCVU9VYjduK2d3aXdwVwpBZnFvRW1XeWliYUVxS3d4djVaaFpVNGlSN002dWJGc0NIMWt3VnNRdDRBNFowSXhieFg2ZnVQYXhnT1dHdkhEClRUZ21hVDZneDJud1Y5bHZMNzlXSkd5MUJaTCtMcHlBaXZNR2U4bi9CTm9MeEJiZ2orRGZWN2M0eWI4RjNBM2cKOUtLU0Myd1ZRVWJHZHBCaWk1Mm45VFhRTW5XTjJNR09TQkVIcmYxVm5UazJyeFZMMWhEVmtxYjMzZHR5S2hWWgpINjloaS9QdXRHbUVmWEI0SVQ2ZGJCNStjR011M0pCZEtGdVpYeVMzbk1zS2x0ZUcwVWlmVzA5V253bGZIS2RiClIxcSt2MHFPTFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUExUEZ6UiswWk9aVmVJaW1EQy9GZGY2N08zb3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUZyVDk4Umc1NUhuWURoRzU0SFZDVXRKQ3MxRkNCSUJnNVVLeGFEMFlEakZ6dE9CeWZSazVZZmhUcG5aCmVVR2ZnYkU2WWc4K3dRQi9NL3FncHRodUpIa1FmZnRhTmkyTDd4bVorZ1NKdVZSNEVoeWZ1VTIvRzNadzhheTgKT1l0MEhOczZ5anNSMWF1bjM5aHFDQmdJenFWUVMyeVFrQUJaTVhpR09GamdFUmVyZWlWTUF4TEsvUGlrK0lNMAp6cFNyV2t3T01TSDZnd2pJU1BrNG00RTJxbVgxaFpDTExMYzRydTBuemJiYmNlMmdETG5qbTAvRWVFUklIZTNWCjdQaWhuRWoxajExUmRudVpBODFmQXQ4Y0p6Yk5TakMzTVdLVDBqWUxVcTBSUTdUV3l4N0cyUG5oUEc4WVQwaG0KcTd2RGFQUCt2UVJrMWlYb2VuMWgxb1l2eEdrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION
